olanguage: csharp
solution: EscherAuth.sln

sudo: false

addons:
  apt:
    packages:
      - nunit-console

script:
  - xbuild /p:Configuration=Release solution-name.sln
  - nunit-console ./EscherAuthTests\bin\Release\EscherAuthTests.dll

